<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class MahasiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Membuat 25 mahasiswa yang akan digunakan untuk berbagai proposal di tahun berbeda
        // Mahasiswa yang sama dapat mengajukan proposal di tahun yang berbeda
        $mahasiswas = [
            // Mahasiswa 1
            [
                'nim' => '2001234567',
                'nama_mhs' => 'I Made Surya Wijaya',
                'prodi_mhs' => 'Teknik Informatika',
                'fakultas_mhs' => 'Fakultas Teknik',
                'no_hp_mhs' => '081234567200',
                'email_mhs' => 'made.surya@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 1,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 2
            [
                'nim' => '2001234568',
                'nama_mhs' => 'I Gusti Ayu Made Sari Dewi',
                'prodi_mhs' => 'Teknik Informatika',
                'fakultas_mhs' => 'Fakultas Teknik',
                'no_hp_mhs' => '081234567201',
                'email_mhs' => 'sari.dewi@student.unud.ac.id    ',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 1,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 3
            [
                'nim' => '2001234569',
                'nama_mhs' => 'I Wayan Gede Suardana',
                'prodi_mhs' => 'Teknik Informatika',
                'fakultas_mhs' => 'Fakultas Teknik',
                'no_hp_mhs' => '081234567202',
                'email_mhs' => 'suardana@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 2,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 4
            [
                'nim' => '2001234570',
                'nama_mhs' => 'I Made Sudarma Putra',
                'prodi_mhs' => 'Matematika',
                'fakultas_mhs' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam',
                'no_hp_mhs' => '081234567203',
                'email_mhs' => 'sudarma.putra@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 2,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 5
            [
                'nim' => '2001234571',
                'nama_mhs' => 'I Gusti Agung Ayu Ratna Dewi',
                'prodi_mhs' => 'Matematika',
                'fakultas_mhs' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam',
                'no_hp_mhs' => '081234567204',
                'email_mhs' => 'ratna.dewi@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 3,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 6
            [
                'nim' => '2001234572',
                'nama_mhs' => 'I Wayan Gede Artawan Eka Putra',
                'prodi_mhs' => 'Matematika',
                'fakultas_mhs' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam',
                'no_hp_mhs' => '081234567205',
                'email_mhs' => 'artawan.eka@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 3,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 7
            [
                'nim' => '2001234573',
                'nama_mhs' => 'I Made Rai Pramana',
                'prodi_mhs' => 'Fisika',
                'fakultas_mhs' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam',
                'no_hp_mhs' => '081234567206',
                'email_mhs' => 'rai.pramana@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 4,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 8
            [
                'nim' => '2001234574',
                'nama_mhs' => 'I Wayan Gede Suharta',
                'prodi_mhs' => 'Fisika',
                'fakultas_mhs' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam',
                'no_hp_mhs' => '081234567207',
                'email_mhs' => 'suharta@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 4,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 9
            [
                'nim' => '2001234575',
                'nama_mhs' => 'I Made Sudiana',
                'prodi_mhs' => 'Fisika',
                'fakultas_mhs' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam',
                'no_hp_mhs' => '081234567208',
                'email_mhs' => 'made.sudiana@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 5,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 10
            [
                'nim' => '2001234576',
                'nama_mhs' => 'I Gusti Ayu Made Sari',
                'prodi_mhs' => 'Kimia',
                'fakultas_mhs' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam',
                'no_hp_mhs' => '081234567209',
                'email_mhs' => 'made.sari@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 5,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 11
            [
                'nim' => '2001234577',
                'nama_mhs' => 'I Wayan Gede Artawan',
                'prodi_mhs' => 'Kimia',
                'fakultas_mhs' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam',
                'no_hp_mhs' => '081234567210',
                'email_mhs' => 'artawan@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 6,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 12
            [
                'nim' => '2001234578',
                'nama_mhs' => 'I Made Sudarsana',
                'prodi_mhs' => 'Kimia',
                'fakultas_mhs' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam',
                'no_hp_mhs' => '081234567211',
                'email_mhs' => 'sudarsana@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 6,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 13
            [
                'nim' => '2001234579',
                'nama_mhs' => 'I Made Surya Putra',
                'prodi_mhs' => 'Biologi',
                'fakultas_mhs' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam',
                'no_hp_mhs' => '081234567212',
                'email_mhs' => 'surya.putra@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 7,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 14
            [
                'nim' => '2001234580',
                'nama_mhs' => 'I Gusti Ayu Sari Lestari',
                'prodi_mhs' => 'Biologi',
                'fakultas_mhs' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam',
                'no_hp_mhs' => '081234567213',
                'email_mhs' => 'sari.lestari@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 7,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 15
            [
                'nim' => '2001234581',
                'nama_mhs' => 'I Wayan Gede Suardika',
                'prodi_mhs' => 'Biologi',
                'fakultas_mhs' => 'Fakultas Matematika dan Ilmu Pengetahuan Alam',
                'no_hp_mhs' => '081234567214',
                'email_mhs' => 'suardika@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 8,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 16
            [
                'nim' => '2001234582',
                'nama_mhs' => 'I Made Sudarma',
                'prodi_mhs' => 'Manajemen',
                'fakultas_mhs' => 'Fakultas Ekonomi dan Bisnis',
                'no_hp_mhs' => '081234567215',
                'email_mhs' => 'made.sudarma@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 8,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 17
            [
                'nim' => '2001234583',
                'nama_mhs' => 'I Gusti Agung Ratna Sari',
                'prodi_mhs' => 'Manajemen',
                'fakultas_mhs' => 'Fakultas Ekonomi dan Bisnis',
                'no_hp_mhs' => '081234567216',
                'email_mhs' => 'ratna.sari@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 9,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 18
            [
                'nim' => '2001234584',
                'nama_mhs' => 'I Wayan Gede Eka Putra',
                'prodi_mhs' => 'Manajemen',
                'fakultas_mhs' => 'Fakultas Ekonomi dan Bisnis',
                'no_hp_mhs' => '081234567217',
                'email_mhs' => 'eka.putra@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 9,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 19
            [
                'nim' => '2001234585',
                'nama_mhs' => 'I Made Rai Wijaya',
                'prodi_mhs' => 'Akuntansi',
                'fakultas_mhs' => 'Fakultas Ekonomi dan Bisnis',
                'no_hp_mhs' => '081234567218',
                'email_mhs' => 'rai.wijaya@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 10,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 20
            [
                'nim' => '2001234586',
                'nama_mhs' => 'I Wayan Suharta Putra',
                'prodi_mhs' => 'Akuntansi',
                'fakultas_mhs' => 'Fakultas Ekonomi dan Bisnis',
                'no_hp_mhs' => '081234567219',
                'email_mhs' => 'suharta.putra@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 10,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 21
            [
                'nim' => '2001234587',
                'nama_mhs' => 'I Made Sudiana Eka',
                'prodi_mhs' => 'Akuntansi',
                'fakultas_mhs' => 'Fakultas Ekonomi dan Bisnis',
                'no_hp_mhs' => '081234567220',
                'email_mhs' => 'sudiana.eka@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 1,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 22
            [
                'nim' => '2001234588',
                'nama_mhs' => 'I Gusti Ayu Sari Purnama',
                'prodi_mhs' => 'Teknik Sipil',
                'fakultas_mhs' => 'Fakultas Teknik',
                'no_hp_mhs' => '081234567221',
                'email_mhs' => 'sari.purnama@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 2,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 23
            [
                'nim' => '2001234589',
                'nama_mhs' => 'I Wayan Artawan Putra',
                'prodi_mhs' => 'Teknik Sipil',
                'fakultas_mhs' => 'Fakultas Teknik',
                'no_hp_mhs' => '081234567222',
                'email_mhs' => 'artawan.putra@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 3,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 24
            [
                'nim' => '2001234590',
                'nama_mhs' => 'I Made Sudarsana Wijaya',
                'prodi_mhs' => 'Teknik Sipil',
                'fakultas_mhs' => 'Fakultas Teknik',
                'no_hp_mhs' => '081234567223',
                'email_mhs' => 'sudarsana.wijaya@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 4,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Mahasiswa 25
            [
                'nim' => '2001234591',
                'nama_mhs' => 'I Made Surya Dharma',
                'prodi_mhs' => 'Teknik Elektro',
                'fakultas_mhs' => 'Fakultas Teknik',
                'no_hp_mhs' => '081234567224',
                'email_mhs' => 'surya.dharma@student.unud.ac.id',
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'email_verified_at' => now(),
                'id_dosen_pembimbing' => 5,
                'team_id' => null,
                'is_ketua' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('mahasiswas')->insert($mahasiswas);
    }
}
